# Generated by Django 5.1.5 on 2025-02-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.CharField(max_length=30, unique=True, verbose_name='TG UserID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last name')),
                ('username', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'TG User',
                'verbose_name_plural': 'TG user',
                'db_table': 'tg_users',
            },
        ),
    ]
