# Generated by Django 5.1.5 on 2025-02-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_learn_model',
            field=models.BooleanField(default=True, verbose_name='Использование обучения модели'),
        ),
    ]
