# Generated by Django 5.1.5 on 2025-02-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tguser_is_learn_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='сount_generations',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во генераций'),
        ),
    ]
