# Generated by Django 5.1.5 on 2025-02-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_payment_сount_generations'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.CharField(default='', max_length=20, verbose_name='Сумма'),
            preserve_default=False,
        ),
    ]
