# Generated by Django 5.1.5 on 2025-02-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.CharField(max_length=30, verbose_name='TG User ID')),
                ('tune_id', models.CharField(max_length=200, unique=True, verbose_name='Tune ID')),
            ],
            options={
                'verbose_name': 'Tune',
                'verbose_name_plural': 'Tunes',
                'db_table': 'tunes',
            },
        ),
    ]
