# Generated by Django 5.1.5 on 2025-02-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tune'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='gender',
            field=models.CharField(default='', max_length=20, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
