# Generated by Django 5.1.5 on 2025-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tune_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
                ('count', models.PositiveIntegerField(default=20, verbose_name='Кол-во')),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Prices List',
                'db_table': 'prices_list',
            },
        ),
        migrations.AddField(
            model_name='tguser',
            name='god_mod',
            field=models.BooleanField(default=False, verbose_name='Режим бога'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='referal',
            field=models.CharField(default='', max_length=30, verbose_name='Реферал'),
        ),
    ]
