# Generated by Django 5.1.5 on 2025-02-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pricelist_tguser_god_mod_tguser_referal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='referal',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Реферал'),
        ),
    ]
