# Generated by Django 5.1.5 on 2025-02-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pricelist_learn_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='sale',
            field=models.CharField(blank=True, default='', help_text='Например: 30%', null=True, verbose_name='Скидка'),
        ),
    ]
