# Generated by Django 5.1.5 on 2025-02-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pricelist_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='learn_model',
            field=models.BooleanField(default=False, verbose_name='Обучение модели'),
        ),
    ]
