# Generated by Django 5.1.5 on 2025-02-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_payment_learn_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_first_payment',
            field=models.BooleanField(default=False, verbose_name='Первый платеж'),
        ),
    ]
