# Generated by Django 5.1.5 on 2025-02-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_tguser_category_tguser_effect_tguser_god_mod_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='gender',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Выбраный пол'),
        ),
    ]
