# Generated by Django 5.1.5 on 2025-02-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_tguser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(max_length=400, unique=True, verbose_name='Slug')),
                ('gender', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=20, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.AddField(
            model_name='tguser',
            name='count_video_generations',
            field=models.PositiveIntegerField(default=3, verbose_name='Кол-во генераций видео'),
        ),
        migrations.CreateModel(
            name='Promt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promts', to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Promt',
                'verbose_name_plural': 'Promts',
                'db_table': 'promts',
            },
        ),
    ]
