# Generated by Django 5.1.5 on 2025-02-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_tguser_count_video_generations'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='type_price_list',
            field=models.CharField(blank=True, choices=[('photo', 'photo'), ('video', 'video')], null=True, verbose_name='Тип списка цен'),
        ),
    ]
