# Generated by Django 5.1.5 on 2025-02-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_tguser_count_video_generations'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='count_video_generations',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во генераций видео'),
        ),
    ]
