# Generated by Django 5.1.5 on 2025-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_payment_count_video_generations'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='has_purchased',
            field=models.BooleanField(blank=True, null=True, verbose_name='Сделал покупку'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя активность'),
        ),
    ]
