# Generated by Django 5.1.5 on 2025-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_tguser_has_purchased_tguser_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='has_purchased',
            field=models.BooleanField(default=True, verbose_name='Сделал покупку'),
        ),
    ]
