# Generated by Django 5.1.5 on 2025-02-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_tguser_has_purchased'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название кампании')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки')),
                ('delay_hours', models.PositiveIntegerField(verbose_name='Задержка в часах')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'newsletters',
            },
        ),
        migrations.AddField(
            model_name='tguser',
            name='sent_messages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
