# Generated by Django 5.1.5 on 2025-02-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_newsletter_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='button',
            field=models.CharField(blank=True, null=True, verbose_name='Название кнопки'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='button_data',
            field=models.CharField(blank=True, null=True, verbose_name='URL или Callback для кнопки'),
        ),
    ]
