# Generated by Django 5.1.5 on 2025-02-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_newsletter_button_newsletter_button_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='button',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='button_data',
        ),
    ]
