# Generated by Django 5.1.5 on 2025-02-20 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_newsletter_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True, verbose_name='Уникальный slug'),
            preserve_default=False,
        ),
    ]
