# Generated by Django 5.1.5 on 2025-02-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_promt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='squeeze',
            field=models.BooleanField(default=False, verbose_name='Дожимка'),
        ),
    ]
