# Generated by Django 5.1.5 on 2025-02-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_newsletter_squeeze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='sent_messages',
            field=models.JSONField(default=list, verbose_name='Отправленные рассылки'),
        ),
    ]
