# Generated by Django 5.1.5 on 2025-02-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_tguser_sent_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='sent_messages',
            field=models.JSONField(default=[0], verbose_name='Отправленные рассылки'),
        ),
    ]
