# Generated by Django 5.1.5 on 2025-02-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_tguser_sent_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='maternity_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материнский платежный ID'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='subscribe',
            field=models.DateField(blank=True, null=True, verbose_name='Подписка до'),
        ),
    ]
