# Generated by Django 5.1.5 on 2025-02-28 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_payment_created_at_tguser_maternity_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_hash', models.CharField(max_length=1000, unique=True, verbose_name='Image hash')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_images', to='main.tguser', verbose_name='TG User')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'tg_images',
            },
        ),
    ]
