# Generated by Django 5.1.5 on 2025-03-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_tgimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tgimage',
            options={'verbose_name': 'TG Image', 'verbose_name_plural': 'TG Images'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
