# Generated by Django 5.1.5 on 2025-03-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_tgimage_options_newsletter_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter', verbose_name='Изображение'),
        ),
    ]
