# Generated by Django 5.1.5 on 2025-03-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_newsletter_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='referral_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество рефералов'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='referral_purchases',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество покупок рефералов'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='reward_generations',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество генераций от рефералов'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='user_purchases_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма покупок пользователя'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='user_purchases_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество покупок пользователя'),
        ),
    ]
