# Generated by Django 5.1.5 on 2025-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_tguser_referral_count_tguser_referral_purchases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='referral_purchases_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма покупок рефералов'),
        ),
    ]
