# Generated by Django 5.1.5 on 2025-03-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_tguser_referral_purchases_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='photo_from_photo',
            field=models.BooleanField(default=False, verbose_name='Режим Фото по фото'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='referral_purchases_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма покупок реферала'),
        ),
    ]
