# Generated by Django 5.1.5 on 2025-03-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_tguser_photo_from_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_renewal',
            field=models.BooleanField(default=False, verbose_name='Продление подписки'),
        ),
    ]
