# Generated by Django 5.1.5 on 2025-03-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_payment_subscription_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='attempt',
            field=models.PositiveIntegerField(default=0, verbose_name='Попытка'),
        ),
    ]
