# Generated by Django 5.1.5 on 2025-03-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_payment_count_learn_model_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='count_generations_for_gift',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во генераций для подарка'),
        ),
    ]
