# Generated by Django 5.1.5 on 2025-03-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_payment_count_generations_for_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='Промо'),
        ),
    ]
