# Generated by Django 5.1.5 on 2025-03-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_payment_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='type_price_list',
            field=models.CharField(blank=True, choices=[('photo', 'photo'), ('video', 'video'), ('promo', 'promo')], null=True, verbose_name='Тип списка цен'),
        ),
    ]
