# Generated by Django 5.1.5 on 2025-03-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_promocode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название'),
        ),
    ]
