# Generated by Django 5.1.5 on 2025-03-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_remove_payment_count_learn_model_alter_tune_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='count_video',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во видео'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='sale',
            field=models.CharField(blank=True, default='', help_text='Например: -30%', null=True, verbose_name='Скидка'),
        ),
    ]
