# Generated by Django 5.1.5 on 2025-03-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_pricelist_count_video_alter_pricelist_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='count_video',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во видео'),
        ),
    ]
