# Generated by Django 5.1.5 on 2025-03-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_pricelist_count_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='api_name',
            field=models.CharField(default='astria', verbose_name='API'),
        ),
        migrations.AddField(
            model_name='tune',
            name='api_name',
            field=models.CharField(default='astria', verbose_name='API'),
        ),
    ]
