version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./static:/app/static
      - ./db.sqlite3:/app/db.sqlite3


  nginx:
    build:
      dockerfile: nginx/Dockerfile  
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/app/static
    depends_on:
      - backend

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    depends_on:
      - backend
    env_file:
      - .env
    restart: always
    volumes:
      - ./media:/app/media
