version: '3.8'

services:
  
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./.docker-volumes/idx_pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    env_file:
      - .env

networks:
 default:
   external: true
   name: astria_bot_shared-web