FROM python:3.12-slim

WORKDIR /app

COPY app/bot/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY .env .
COPY media/logo_p.png media/
COPY app/bot/ .

ENV BACKEND_API_URL=http://backend:8000

CMD ["python", "main.py"]