version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.docker-volumes/idx_pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - postgres
      - redis

  nginx:
    build:
      dockerfile: ./nginx-app/Dockerfile
    container_name: nginx
    ports:
      - "8002:80"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - backend
    env_file:
      - .env_web

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    depends_on:
      - backend
    env_file:
      - .env
    restart: always
    volumes:
      - ./media:/app/media

networks:
 default:
   external: true
   name: astria_bot_shared-web