services:

  postgres_host:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    networks:
      - shared_network
    volumes:
      - ./.docker-volumes/idx_pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7
    ports:
      - "6378:6379"
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    networks:
      - shared_network

networks:
  shared_network:
    external: true
