FROM python:3.12-slim

WORKDIR /app

COPY app/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

COPY .env .
COPY app/backend/ .

ENV DJANGO_SETTINGS_MODULE=config.settings


# ENTRYPOINT ["sh", "/app/entrypoint.sh"]
