version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - .env
      
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - .env
    restart: always

networks:
  app-network:
    driver: bridge
