version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    volumes:
      - ./static:/app/static
      - ./media:/app/media

  nginx:
    build:
      dockerfile: ./nginx-app/Dockerfile.stage
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - backend

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    depends_on:
      - backend
    env_file:
      - .env
    restart: always
    volumes:
      - ./media:/app/media
