version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    volumes:
      - ./static:/app/static
      - ./media:/app/media

  nginx:
    build:
      dockerfile: ./nginx-app/Dockerfile
    container_name: nginx
    ports:
      - "8002:80"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - backend
    env_file:
      - .env_web

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    depends_on:
      - backend
    env_file:
      - .env
    restart: always
    volumes:
      - ./media:/app/media

networks:
 default:
   external: true
   name: astria_bot_shared-web