FROM python:3.12-slim

WORKDIR /app

# Копируем requirements.txt и устанавливаем зависимости
COPY app/bot/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY .env .
COPY logo_p.png .
# Копируем все файлы бота в контейнер
COPY app/bot/ .

# Устанавливаем переменные окружения для общения с backend
ENV BACKEND_API_URL=http://backend:8000

# Запускаем бота
CMD ["python", "main.py"]