FROM python:3.12-slim

WORKDIR /app/backend

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/backend/ .

ENV DJANGO_SETTINGS_MODULE=config.settings

RUN python manage.py collectstatic --noinput
RUN python manage.py migrate --noinput

RUN pip install gunicorn

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]