services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.docker-volumes/idx_pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env